version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
cache: '%LOCALAPPDATA%\vcpkg\archives'

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%

before_build:
  - cmake -G "Visual Studio 16 2019" -A x64 -DNIGHTLY_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: minimal
artifacts:
  - path: Debug\devilutionx.exe
    name: devilutionx.exe
